[package]
name = "aoc-2021-day-02"
version = "0.1.0"
edition = "2021"
authors = ["Jake Ledoux <contactjakeledoux@gmail.com>"]

[lib]
doctest = false

[[bin]]
name = "aoc-2021-day-02"
test = false

[features]
