[package]
name = "aoc-2021-day-21"
version = "0.1.0"
edition = "2021"
authors = ["Jake Ledoux <contactjakeledoux@gmail.com>"]

[lib]
doctest = false

[[bin]]
name = "aoc-2021-day-21"
test = false

[features]

[dependencies]
cached = "0.26.2"
rayon = "1.5.1"
