name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests (2022)
      run: |
        cd 2022
        cargo test --verbose
    - name: Run tests (2021)
      run: |
        cd 2021
        cargo test --verbose
    - name: Run tests (2019)
      run: |
        cd 2019
        cargo test --verbose
